config/routes.rb
Rails.application.routes.draw do
  devise_for :admins

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  resources :posts
  resources :users
  root 'sessions#new'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord

    belongs_to :user

    STATUS = {
        pending: "pending",
        scheduled: "scheduled",
        running: "running"
    }

    enum status: STATUS

    def self.status_options
        STATUS.map { |key, value| [key.capitalize, value] }
    end
end

app/models/user.rb
class User < ApplicationRecord
    has_many :posts
    validates_uniqueness_of :user_num
    before_validation :ensure_unique_user_num, on: :create

    STATUS = {
        watch: "watch",
        author: "author",
    }

    enum status: STATUS

    def self.status_options
        STATUS.map { |key, value| [key.capitalize, value] }
    end

    private
  
    def ensure_unique_user_num
        self.user_num ||= generate_unique_user_num
    end
    
    def generate_unique_user_num
        loop do
          num = rand(100000..999999)
          break num unless User.exists?(user_num: num)
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include SessionsHelper

    def after_sign_in_path_for(resource)
        users_path
    end

    def after_sign_out_path_for(resource)
        root_path
    end

    private

    def logged_in_user
        unless logged_in?
          flash[:alert] = "Please log in."
          redirect_to login_url
        end
      end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :logged_in_user

  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.update(post_params)
    authorize! @post 

    redirect_to posts_path
  end

  def destroy 
    @post = Post.find(params[:id])
    authorize! @post 
    @post.destroy
    redirect_to posts_path
  end

  def create
    @post = Post.new(post_params)
    authorize! @post 
    @post.user_id = current_user.id
    @post.save
    redirect_to posts_path
  end
  private
  def post_params
      params.require(:post).permit(:title, :description, :status, :user_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    include SessionsHelper

    def new
    end
    
    def create
        user = User.find_by(user_num: params[:session][:user_num])
        if user
            log_in user
            redirect_to posts_path        
        else
          flash[:alert] = 'Wrong number or password'
        end
    end

    def destroy
        log_out
        redirect_to root_path
    end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_admin!

    def index
        @users = User.all
      end
    
      def show
        @user = User.find(params[:id])
      end
    
      def new
        @user = User.new
        @user.user_num = generate_unique_user_num
      end
    
      def edit
        @user = User.find(params[:id])
      end
    
      def update
        user = User.find(params[:id])
        user.update(user_params)
    
        redirect_to users_path
      end
    
      def destroy 
        user = User.find(params[:id])
        user.destroy
        redirect_to users_path
      end
    
      def create
        user = User.new(user_params)
        user.save
        redirect_to users_path
      end

      private

      def user_params
          params.require(:user).permit(:name, :status, :user_num)
      end

      def generate_unique_user_num
        loop do
          user_num = rand(100000..999999)
          break user_num unless User.exists?(user_num: user_num)
        end
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def log_in(user)
        session[:user_id] = user.id
    end
    
    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end
    
    def logged_in?
        !current_user.nil?
    end
    
    def log_out
        session.delete(:user_id)
        @current_user = nil
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet"   href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>CrudApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<div class="container">
  <div class="row justify-content-center">
    <h4 class="mt-4 mb-4 display-4">Edit Post</h4>
  </div>

  <div class="row justify-content-center">
  <div class="row justify-content-center new-post">
    <%= form_with(model: @post, local: true) do |form| %>
      <div class="form-group">
        <%= form.label :title %>
        <%= form.text_field :title, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= form.label :description %>
        <%= form.text_area :description, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= form.label :status %>
        <%= form.select(:status, options_for_select(Post.status_options))  %>
      </div>
      <div class="form-group">
        <%= form.submit class: 'form-control btn-primary' %>
      </div>
    <% end %>
  </div>
  </div>
</div>

<div class="cancel-container">
  <%= link_to "Cancel", posts_path, class: 'cancel' %>
</div>

app/views/posts/index.html.erb
<div class="container">
  <div class="user-title-container">
    <div></div>
    <h1 class="user-title">Listing Posts</h1>
    <div class="logout-container">
      <%= button_to "Sign out", logout_path, class:'logout', method: :delete %>
    </div>
  </div>

  <div class="button-create-container">
    <% if allowed_to?(:create?, Post) %>
      <%= link_to 'Create Post', new_post_path, class: 'button-create' %>
    <% end %>
  </div>

  <div class="notes-container">
    <% if @posts.present? %>
      <div class="notes-grid">
        <% @posts.each do |post| %>
          <div class="note-item">
            <div class="notes-header">
            <% if allowed_to?(:destroy?, record: post) %>
              <p><%= link_to 'X', post_path(post.id), data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'} %></p>
            <% end %>            
            </div>
            <h2><%= post.title %></h2>
            <p><%= post.description %></p>
            <p><b>status:</b> <%= post.status %></p>
            <div class="post-buttons">
              <%= link_to 'Show', post_path(post.id), class: 'buttons-post' %>
              <% if allowed_to?(:update?, record: post) %>
                <%= link_to 'Edit', edit_post_path(post.id), class: 'buttons-post' %> 
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
    <%else%> 
      <div class="p-3 mb-2 bg-light text-dark">
        <span class="text-info font-weight-bold">Welcome! </span>
        Create your first post
      </div>
    <%end%>
  </div>

</div>

app/views/posts/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <h4 class="mt-4 mb-4 display-4">New Post</h4>
  </div>

  <div class="row justify-content-center">
  <div class="row justify-content-center new-post">
    <%= form_with scope: :post, url: posts_path, local: true do |form| %>
      <div class="form-group">
        <%= form.label :title %>
        <%= form.text_field :title, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label :description %>
        <%= form.text_area :description, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label :status %>
        <%= form.select(:status, options_for_select(Post.status_options))  %>
      </div>

      <div class="form-group">
        <%= form.submit class: 'form-control btn-primary' %>
      </div>
    <% end %>
  </div>
  </div>
</div>

<div class="cancel-container">
  <%= link_to "Cancel", posts_path, class: 'cancel' %>
</div>

app/views/posts/show.html.erb
<div class="container">
  <div class="row justify-content-center">
    <h4 class="mt-4 mb-4 display-4">Show details of post <%= @post.id %> made by <%= @post.user_id%></h4>
  </div>

  <div class="row justify-content-center">
    <div class="show-post" >
      <div>
          <h4>Title:</h4>
          <p><%= @post.title %></p>
          <h4>Description:</h4>
          <p><%= @post.description %></p>
      </div>
    </div>
  </div>
</div>


<div class="cancel-container">
  <%= link_to "Back", posts_path, class: 'cancel' %>
</div>

app/views/users/edit.html.erb
<div class="container">
  <div class="row justify-content-center">
    <h4 class="mt-4 mb-4 display-4">Edit User</h4>
  </div>

  <div class="row justify-content-center">
  <div class="row justify-content-center new-user">
    <%= form_with(model: @user, local: true) do |form| %>

      <div class="form-group">
        <%= form.label :name %>
        <%= form.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label :user_num, "User Number (generated)" %>
        <%= form.number_field :user_num, readonly: true %>
      </div>

      <div class="form-group">
        <%= form.label :status %>
        <%= form.select(:status, options_for_select(User.status_options))  %>
      </div>
      <div class="form-group">
        <%= form.submit class: 'form-control btn-primary' %>
      </div>
    <% end %>
  </div>
  </div>
</div>

<div class="cancel-container">
  <%= link_to "Cancel", users_path, class: 'cancel' %>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="user-title-container">
    <div></div>
    <h1 class="user-title">Listing Users</h1>
    <div class="logout-container">
      <%= button_to "Sign out", destroy_admin_session_path, class:'logout', method: :delete %>
    </div>
  </div>
  
  <div class="button-create-container">
  <%= link_to 'Create User', new_user_path, class: 'button-create' %>
  </div>

  <% if @users.present? %>
    <div class="row justify-content-center">
      <table class="table table-bordered">
        <thead>
          <tr>
            <th scope="col">Name</th>
            <th scope="col">User Number</th>
            <th scope="col">Status</th>
            <th scope="col" colspan="3">Action</th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= user.name %></td>
              <td><%= user.user_num %></td>
              <td><%= user.status %></td>
              <td><%= link_to 'Show', user_path(user.id) %></td>
              <td><%= link_to 'Edit', edit_user_path(user.id) %></td>  
              <td><%= link_to 'Delete', user_path(user.id), data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'} %></td>           
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  <% else %>
    <div class="p-3 mb-2 bg-light text-dark">
      <span class="text-info font-weight-bold">Welcome! </span>
      Create user
    </div>
  <% end %>



</div>

app/views/users/new.html.erb
<div class="container ">
  <div class="row justify-content-center">
    <h4 class="mt-4 mb-4 display-4">New User</h4>
  </div>
  
  <div class="row justify-content-center">
  <div class="row justify-content-center new-user">
    <%= form_with scope: :user, url: users_path, local: true do |form| %>
    
      <div class="form-group">
        <%= form.label :name %>
        <%= form.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label :user_num, "User Number (generated)" %>
        <%= form.number_field :user_num, readonly: true %>
      </div>

      <div class="form-group">
        <%= form.label :status %>
        <%= form.select(:status, options_for_select(User.status_options))  %>
      </div>

      <div class="form-group">
        <%= form.submit class: 'form-control btn-primary' %>
      </div>
    <% end %>
  </div>
  </div>
</div>

<div class="cancel-container">
  <%= link_to "Cancel", users_path, class: 'cancel' %>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row justify-content-center">
    <h4 class="mt-4 mb-4 display-4">Show details of post <%= @user.id %></h4>
  </div>
  <div class="row justify-content-center">
    <table class="table">
      <tbody>
        <tr>
          <th>Name:</th>
          <td><%= @user.name %></td>
        </tr>
        <tr>
          <th>User Number:</th>
          <td><%= @user.user_num %></td>
        </tr>
        <tr>
          <th>Status:</th>
          <td><%= @user.status %></td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

<div class="cancel-container">
  <%= link_to "Back", users_path, class: 'cancel' %>
</div>